const MAIN_BANNER_HEIGHT = 349;
const MAIN_BANNER_BOTTOM_POSITION = 34;
const HEADER_BANNER_HEIGHT_PLUS_TOP = 108;
const MAIN_BANNER_HEIGHT_PLUS_BOTTOM =
	MAIN_BANNER_HEIGHT + MAIN_BANNER_BOTTOM_POSITION;

const MAIN_BANNER_POSITION = {
	TOP: { top: 88 },
	BOTTOM: { bottom: 88 }
};

export {
	HEADER_BANNER_HEIGHT_PLUS_TOP,
	MAIN_BANNER_HEIGHT_PLUS_BOTTOM,
	MAIN_BANNER_POSITION
};
